# Generated by Django 3.2.5 on 2021-08-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amiibo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
